#!/bin/bash

RESULT=0
declare -a tests failed

# Find tests to execute
if [ $# -ne 0 ]
then
    tests=$@
else
    tests=($(dirname "$0")/test????-*)
fi

for t in ${tests[@]}
do
    $t
    if [ $? -ne 0 ]
    then
        RESULT=1
        failed+=($t)
    fi
done

if [ ${#failed[@]} -ne 0 ]
then
    echo >&2 "Some tests failed:"
    for t in ${failed[@]}
    do
        echo >&2 $t
    done
fi

exit $RESULT
