#!/bin/bash

RESULT=0
declare -a tests failed

tests=($(dirname "$0")/test????-*)

if [ $# -ne 0 ]
then
    tests=$@
fi

for t in $tests
do
    $t
    [ $? -ne 0 ] && RESULT=1
    failed+=($t)
done

if [ ${#failed[@]} -ne 0 ]
then
    echo >&2 "Some tests failed:"
    for t in ${failed[@]}
    do
        echo >&2 $t
    done
fi

exit $RESULT
